platform:
  - x86
  - x64
environment:
  OPENSSL_LIBS: ssleay32:libeay32
  matrix:
    - RUST_VERSION: stable
      TARGET: msvc
    - RUST_VERSION: stable
      TARGET: gnu
    - RUST_VERSION: beta
      TARGET: msvc
    - RUST_VERSION: beta
      TARGET: gnu
    - RUST_VERSION: nightly
      TARGET: msvc
    - RUST_VERSION: nightly
      TARGET: gnu
matrix:
  allow_failures:
    - TARGET: msvc
      platform: x86
    - RUST_VERSION: nightly
cache:
  - target\debug\build
  - target\debug\deps
  - '%USERPROFILE%\.cargo'
install:
  - ps: |
        $env:PATH += ";C:\rust\bin";
        if ($env:platform -eq 'x86') {
          $arch_expanded = "i686-pc-windows-${env:TARGET}";
          $env:ARCH = "x86";
          $env:bits = "32";
        } else {
          $arch_expanded = "x86_64-pc-windows-${env:TARGET}";
          $env:ARCH = "amd64";
          $env:bits ="64";
        }
        $env:OPENSSL_INCLUDE_DIR = "C:\OpenSSL-Win${env:bits}\include";
        $env:OPENSSL_LIB_DIR = "C:\OpenSSL-Win${env:bits}\lib";
        if ($env:TARGET -eq 'gnu') {
          $env:PATH += ";C:\msys64\mingw${env:bits}\bin";
          gcc --version;
        }
        if ($env:RUST_VERSION -eq 'stable') {
          echo "Downloading $channel channel manifest";
          Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable";

          $env:RUST_VERSION = Get-Content channel-rust-stable | Select -first 1 | %{$_.split('-')[1]}
        }
        $env:rust_installer = "rust-${env:RUST_VERSION}-${arch_expanded}.exe";
  - curl --show-error --location --retry 5 --output rust-installer.exe https://static.rust-lang.org/dist/%rust_installer%
  - .\rust-installer.exe /VERYSILENT /NORESTART /DIR="C:\rust"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo test --verbose --no-default-features
