sudo: false
language: rust

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev # needed for --verify

os:
- linux
- osx

cache:
  apt: true
  cargo: true

rust:
- nightly
- beta
- stable

# From https://github.com/japaric/rust-everywhere
matrix:
  # Clear the whole matrix
  exclude:
  - os: linux
  - os: osx
  - rust: nightly
  - rust: beta
  - rust: stable
  include:
  - os: linux # 32-bit Linux (glibc)
    rust: stable
    env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages:
          - libcurl4-gnutls-dev # different curl to not conflict with i386 openssl
          - libelf-dev
          - libdw-dev
          - binutils-dev # needed for --verify
          - gcc-multilib # Cross compiler and cross compiled C libraries
          - libssl-dev:i386
  - os: linux # 32-bit Linux (glibc)
    env: TARGET=i686-unknown-linux-gnu
    rust: beta
    addons:
      apt:
        packages:
          - libcurl4-gnutls-dev # different curl to not conflict with i386 openssl
          - libelf-dev
          - libdw-dev
          - binutils-dev # needed for --verify
          - gcc-multilib # Cross compiler and cross compiled C libraries
          - libssl-dev:i386
  - os: linux # 32-bit Linux (glibc)
    rust: nightly
    env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages:
          - libcurl4-gnutls-dev # different curl to not conflict with i386 openssl
          - libelf-dev
          - libdw-dev
          - binutils-dev # needed for --verify
          - gcc-multilib # Cross compiler and cross compiled C libraries
          - libssl-dev:i386
  - os: linux # 64-bit Linux (glibc)
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux # 64-bit Linux (glibc)
    rust: beta
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux # 64-bit Linux (glibc)
    rust: nightly
    env: TARGET=x86_64-unknown-linux-gnu
  # 64-bit Linux (musl) doesn't work with openssl
  - os: osx # 32-bit OSX
    rust: stable
    env: TARGET=i686-apple-darwin
  - os: osx # 32-bit OSX
    rust: beta
    env: TARGET=i686-apple-darwin
  - os: osx # 32-bit OSX
    rust: nightly
    env: TARGET=i686-apple-darwin
  - os: osx # 64-bit OSX
    rust: stable
    env: TARGET=x86_64-apple-darwin
  - os: osx # 64-bit OSX
    rust: beta
    env: TARGET=x86_64-apple-darwin
  - os: osx # 64-bit OSX
    rust: nightly
    env: TARGET=x86_64-apple-darwin
  allow_failures:
  - rust: nightly

before_install: ci/before_install.sh
before_script: ci/before_script.sh
script: ci/script.sh
after_success: ci/after_success.sh

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE='lint'
  - PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
  # encrypted github token for doc upload
  - secure: "MP9oviNLDqK73nD3al+rGnrFnyhgSLFK9OhzCLNxzOhNieE9LDW4VJ+crIiUI62TPimx/nrMPYQssVQW9yivM+YWBiSjK/IDmGJrX1+xUN9XlQemKIlv+Ms1eTfzoRMcraiPILCBNc0OhqwCferHQhxEjzXpmUAjFmt8Qgb4vpdGxhvLU1f3dRk6fwIQgLsfKIqXzHczfQmGJ2eF76PLgaUtL4IYP3ogmtmOid7UD/4FEAsDcr+UNSza4u0ABRz8lEe6JCPEARQvETaKMuih21qxFnQubWiJGnH8r6p5Zvo+MDz/I5L9bLia1MCH1gUXtjzaV2naB5ozcMANZYsjvUkrSvCRn9bcccNUXNizNRWR8aQgFmytif+2uTQ8F8nDb3hg0/Et6mzroXmBPzm0B0AlV3SiAvW1odS/9WBXOATM7KRrxRgfD/R+65vWrYAgPFupvmPYXCR4mr96AgZMoU3lHjf8dIk5EyVK1rJJMtvIBQovgPDCjVhVoNh5Wyp5dG2uAH7LC18iokKt4mxfI5IEcPw94y4wodHgwn1Z0hTgBvxnwmZm1QZkOZpqAVJgSt2soZXw2n1WbEwskV39l+XNJOZ3lxKcdIxW2xY+NXLJy9sQ7nXekYHizXZb7EeD5TQWENIN9Cf6NLf8J7Z3IU4wG66gi0/HlJdfsvmAujQ="
